
image: ubuntu:22.04

pipelines:
  branches:
    master:
    - step:
        name: a simple demo case for builing project in docker
        script:
          - dpkg-divert --local --rename --add /sbin/initctl
          - ln -sf /bin/true /sbin/initctl
          - DEBIAN_FRONTEND=noninteractive
          - dpkg --add-architecture i386 
          - apt-get update 
          - apt-get -y install gcc-avr binutils-avr avr-libc gdb-avr avrdude  make git  sudo curl tree nano lrzsz
          - cd ./src/Doku_Test
          - make hex