#  Template publish .NET Core package to nuget.org

#  This template allows you to publish your .NET Core package to nuget.org.
#  The workflow allows running tests, code linting and security scans on feature branches (as well as master).
#  The .NET Core package will be validated and published after the code is merged to master.

# Prerequisites: $NUGET_SECRET_API_KEY setup as deployment variables.

# To run your pipeline on a Windows machine, create a self-hosted Windows runner.
# For instructions on setting up a Windows runner, see https://support.atlassian.com/bitbucket-cloud/docs/set-up-runners-for-windows/

image: ubuntu:22.04

pipelines:
  branches:
    master:
    - step:
        name: a simple demo case for builing project in docker
        script:
          - dpkg-divert --local --rename --add /sbin/initctl
          - ln -sf /bin/true /sbin/initctl
          - DEBIAN_FRONTEND=noninteractive
          - dpkg --add-architecture i386 
          - apt-get update 
          - apt-get -y install gcc-avr binutils-avr avr-libc gdb-avr avrdude  make git  sudo curl tree nano lrzsz
          - cd ./src/Doku_Test
          - make hex