name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dpkg-divert
      run: |
        sudo dpkg-divert --local --rename --add /sbin/initctl
        sudo ln -sf /bin/true /sbin/initctl
        DEBIAN_FRONTEND=noninteractive
        sudo dpkg --add-architecture i386  
        
    - name: install build tools
      run: |
        sudo apt-get update 
        sudo apt-get -y install gcc-avr binutils-avr avr-libc gdb-avr avrdude  make git  sudo curl tree nano lrzsz
        
    - name: build project using make
      run: |
        cd ./src/Doku_Test
        make hex
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: all skeleton-files
        path: |
          ./src/Doku_Test/skeleton.*
